### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ervee**
Added nginx comment and some other changes to the readme. See what you can use. Next update will be the nginx config documentation.

### CODE REVIEW

**Comment by robertvandenbaar** [comment]
Hmm, the sudo -u for the composer install is not needed by the way. Well, the user needs to be able to read the files but nothing more. And yes, please send the me your complete nginx config file so I can include it in the documentation.

**Comment by ervee** [comment]
In my installation the SSH user does not have the proper rights to write or change files in the web directory. Sometimes even not read access, that's why I execute it with the ```sudo -u www-data``` in my case. You could remove or change the readme to be more clear on this.

**Comment by robertvandenbaar** [comment]
Could you send your nginx configuration. I would like to include it (and probably use it as well).

**Comment by ervee** [comment]
The following is the virtual server bit for nginx:

```
upstream php-handler {
	# Use TCP or socket for the connection to PHP-FPM
	#server 127.0.0.1:9000;
	server unix:/run/php/php7.0-fpm.sock;
}

server {
	listen 80;
	listen [::]:80;
	server_name your_fqdn_here;
	error_page 403 404 /404.html;
	# It's 2018... Redirect any to HTTPS!
	return 301 https://$server_name$request_uri;
	access_log /var/log/nginx/your_fqdn_here-access.log;
	error_log /var/log/nginx/your_fqdn_here-error.log;
}

server {
	# Remove "http2" bit if your server version does not support it or you don't want it
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
	ssl_certificate /etc/ssl/private/your_cert_here.crt;
	ssl_certificate_key /etc/ssl/private/your_key_here.key;

	server_name your_fqdn_here;
	error_page 403 404 /404.html;

	root /srv/www/vhosts/my_fancy_website/htdocs/;
	access_log /var/log/nginx/my_fancy_website-access-ssl.log;
	# To debug, add "debug" at the end of the error_log line (before the ; line end)
	error_log /var/log/nginx/my_fancy_website-error-ssl.log;
	index index.php index.html;

	location / {
		try_files $uri $uri/ =404;
		# The next two lines are for basic authentication. Only use it with HTTPS!
		auth_basic "Restricted Content";
		auth_basic_user_file /srv/www/auth/.htpasswd-my_fancy_website.auth;
		# I have LDG in a subdirectory, so I (temporarily) redirect / to the LDG directory
		# This way I can easily switch gallery software without having users learn a new URL		
		return 302 https://$server_name/LDG/;
	}

	location ~ /\.ht {
		deny all;
	}

	location ~ /\.gitignore {
		deny all;
	}

	location ~ /cron.php {
		deny all;
	}

	location ~ /settings.json {
		deny all;
	}

	location /LDG/ {
		try_files $uri $uri/ /LDG/index.php?$args;
		# The next two lines are for basic authentication. Only use it with HTTPS!
		auth_basic "Restricted Content";
		auth_basic_user_file /srv/www/auth/.htpasswd-my_fancy_website.auth;
	}

	location ~ ^/LDG/.*\.php$ {
		# The next two lines are for basic authentication. Only use it with HTTPS!
		auth_basic "Restricted Content";
		auth_basic_user_file /srv/www/auth/.htpasswd-my_fancy_website.auth;
		include snippets/fastcgi-php.conf;
		fastcgi_pass php-handler;
	}
}
```

My /etc/nginx/snippets/fastcgi-php.conf (probably default):

```
# regex to split $uri to $fastcgi_script_name and $fastcgi_path
fastcgi_split_path_info ^(.+\.php)(/.+)$;

# Check that the PHP script exists before passing it
try_files $fastcgi_script_name =404;

# Bypass the fact that try_files resets $fastcgi_path_info
# see: http://trac.nginx.org/nginx/ticket/321
set $path_info $fastcgi_path_info;
fastcgi_param PATH_INFO $path_info;

fastcgi_index index.php;
include fastcgi.conf;
```

My /etc/nginx/fastcgi.conf (probably default):

```
fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
```

**Comment by robertvandenbaar** [comment]
Great! I've added it to the [Wiki](https://github.com/robertvandenbaar/LDG/wiki/Configure-LDG-for-Nginx).

**Pull request merged**
